- hosts: all
  tasks:
    # sudo apt update; sudo apt install openjdk-17-jdk-headless

$ cat /etc/systemd/system/mc_server.service
[ Unit ]
Description=Just MC Server

[ Service ]
WorkingDirectory=/home/ubuntu/mc_server
ExecStart=/home/ubuntu/mc_server/start_server.sh
Restart=always

[ Install ]
WantedBy=multi-user.target

$ cat start_server.sh
#!/bin/bash

java -Xmx1024M -Xms1024M -jar /home/ubuntu/mc_server/server.jar nogui --port=12221